# Generated by Django 2.2 on 2019-11-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying_selling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangMua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('cover', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
