# Generated by Django 2.2 on 2019-11-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying_selling', '0002_dangmua'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangban',
            name='product_price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
