# Generated by Django 2.2 on 2019-11-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying_selling', '0003_dangban_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dangban',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='dangmua',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='dangban',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dangban',
            name='link_Facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='dangban',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Publish')], default=0),
        ),
        migrations.AddField(
            model_name='dangmua',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dangmua',
            name='link_Facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='dangmua',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Publish')], default=0),
        ),
    ]
