# Generated by Django 2.2 on 2019-11-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying_selling', '0004_auto_20191110_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dangban',
            name='status',
            field=models.IntegerField(choices=[(0, 'Chưa được kiểm duyệt'), (1, 'Đã được kiểm duyệt')], default=0),
        ),
        migrations.AlterField(
            model_name='dangmua',
            name='status',
            field=models.IntegerField(choices=[(0, 'Chưa được kiểm duyệt'), (1, 'Đã được kiểm duyệt')], default=0),
        ),
    ]
